#!/usr/bin/env bash
# transfers file from system to server
FILE_PATH="$1"
USER_IP="$2"
USERNAME="$3"
SSH_PKEY="$4"
if [ "$#" -gt "3" ];
then
    scp -o StrictHostKeyChecking=no -i "$SSH_PKEY" "$FILE_PATH" "$USERNAME@$USER_IP:~/"
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi