#!/usr/bin/env bash
# installing nginx in the web server

sudo apt update
sudo apt install -y nginx

sudo sed -i "s/listen 80 default_server;/listen 80;/" /etc/nginx/sites-available/default
sudo sed -i "s/listen \[::\]:80 default_server;/listen \[::\]:80;/" /etc/nginx/sites-available/default

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -s reload
sudo update-rc.d nginx defaults
