#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get install -y nginx

cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.back

text_to_replace="server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

if grep -qF "return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" "/etc/nginx/sites-available/default"; then
	sed -i "s|server_name _;|$text_to_replace|" /etc/nginx/sites-available/default
	echo "$text_to_replace REPLACEMENT DONE"
else
	echo "this text already exist"
fi

sudo nginx -s reload
