#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By

HOST_NAME=$(hostname)

# code to configure redirect for a single page(/redirect_me) and add header to display hostname
string_for_replacement="location / {\n\t\tadd_header X-Served-By $HOST_NAME;"

if ! grep -qF "add_header X-Served-By $HOST_NAME;" "/etc/nginx/sites-enabled/default";then
    sudo sed -i "s|location / {|$string_for_replacement|" /etc/nginx/sites-enabled/default
    echo "Replacement done."
else
    echo "The string is already present in the file. No changes made."
fi

# restart the web server after updating the settings
sudo nginx -s reload
