#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server

# Update package list and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Define variables
STUDENT_ID="471117"
WEB_SERVER_1="${STUDENT_ID}-web-01"
WEB_SERVER_2="${STUDENT_ID}-web-02"

#configure haproxy
AddB_AddF=$(cat << 'EOF'
errorfile 504 /etc/haproxy/errors/504.http
frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server $WEB_SERVER_1 52.91.121.37:80 check
    server $WEB_SERVER_2 54.90.38.48:80 check
EOF
)

FILE_PATH="/etc/haproxy/haproxy.cfg"

if ! grep -qF "$AddB_AddF" "$FILE_PATH";then
    echo "$AddB_AddF" | sudo tee -a "$FILE_PATH"
    echo "Replacement done."
else
    echo "The string is already present in the file. No changes made."
fi

# Enable HAproxy service
sudo systemctl enable haproxy

# Start HAproxy service
sudo systemctl start haproxy

# Verify HAproxy status
sudo systemctl status haproxy

echo "HAproxy has been installed and configured to distribute traffic to ${WEB_SERVER_1} and ${WEB_SERVER_2} using the roundrobin algorithm."
