#!/usr/bin/env bash
# debugging nginx port 80
# Solution: delete the existing ../sites-enabled/defaul,
# and replace it with a copy of../sites-available/default. 
# -f deletes the existing file and replaces it
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo nginx -s reload
