#!/usr/bin/env bash
# Function to clean up and exit

trap 'echo "I hate the kill command"' SIGTERM

# Function to handle SIGINT (Ctrl+C)
trap 'echo "Y U no love me?!"' SIGINT

# Function to handle SIGTERM or SIGQUIT (kill or kill -s QUIT)
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit 0' SIGTERM SIGQUIT

# Create PID file
echo $$ > /var/run/myscript.pid

# Main loop (infinite)
while true; do
  echo "To infinity and beyond"
  sleep 1
done
