#!/usr/bin/env bash
# Path to the file

file="/etc/passwd"

# Read the file line by line using a while loop
while IFS=: read -r username _ uid _ _ home _
do
    # Display the username, user id, and home directory
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < "$file"

