#!/usr/bin/env bash
# Path to the file

file="/etc/passwd"

# Read the file line by line using a while loop and IFS
while IFS=: read -r username _ _ gid _ home shell
do
    # Extract additional information from the user ID field
    user_info=$(grep -E "^${username}:" /etc/passwd | cut -d ':' -f 5)

    # Extract the password field from the user's entry
    password=$(grep -E "^${username}:" /etc/passwd | cut -d ':' -f 2)

    # Display the story
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell.User ID's place is protected by the passcode $password, more info about the user here: $user_info"
done < "$file"

