#!/usr/bin/env bash
# prints best school 10 times

num=1

while [ $num -le 10 ]
do
	echo "Best School"
	if [ $num -eq 4 ]
	then
		echo "bad luck"
	elif [ $num -eq 8 ]
	then
		echo "good luck"
	fi
	((num++))
done

