#!/usr/bin/env bash
# print for, 12hours to 59minutes

hours=0

while [ $hours -le 12 ]
do
	minutes=1
	echo "Hour: $hours"
	while [ $minutes -le 59 ]
	do
		echo $minutes
		((minutes++))
	done
	((hours++))
done

