#!/usr/bin/env bash
#set a ip adderss

# Update hosts file
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

# Flush DNS cache (optional, but recommended)
systemctl restart systemd-resolved

